#!/bin/sh
clear
echo "COMPILING ===========================================================\n"
rm testing
gcc -O3 -ansi -Wall Board.* Move.* Util.* Search.* Evaluate.* tests.c -o testing

echo "\nRUNNING =============================================================\n"

time ./testing

echo "\nDONE ================================================================\n"
