#!/bin/sh
clear
echo "COMPILING ===========================================================\n"
rm testing
gcc -O3 -ansi -Wall board.h board.c tests.c -o testing

echo "\nRUNNING =============================================================\n"
./testing
echo "\nDONE ================================================================\n"
